export const products = [
  {
    id: 1,
    name: "black silvered men's watch",
    price: 122.99,
    category: "watches",
    description: "",
    quantity: 1,
    rating: 3.6,
    img: "/images/products/13.jpg",
  },
  {
    id: 2,
    name: "u-boat watch",
    price: 121.19,
    category: "watches",
    description: "",
    quantity: 1,
    rating: 4.5,
    img: "/images/products/11.jpg",
  },
  {
    id: 4,
    name: "Rolex golden watch",
    price: 92.06,
    category: "watches",
    description: "",
    quantity: 1,
    rating: 2.7,
    img: "/images/products/22.jpg",
  },
  {
    id: 5,
    name: "Hp pavillion",
    price: 537.89,
    category: "electronics",
    description: "",
    quantity: 1,
    rating: 1,
    img: "/images/products/20.jpg",
  },
  {
    id: 3,
    name: "golden men's watch",
    price: 76.12,
    category: "watches",
    description: "",
    quantity: 1,
    rating: 3.6,
    img: "/images/products/7.jpg",
  },
  {
    id: 6,
    name: "Fitted men's suits",
    price: 163.23,
    category: "clothes",
    description: "",
    quantity: 1,
    rating: 2.8,
    img: "/images/products/21.jpg",
  },
  {
    id: 7,
    name: "Long sleveed toplet",
    price: 26.99,
    category: "clothes",
    description: "",
    quantity: 1,
    rating: 1.2,
    img: "/images/products/18.jpg",
  },
  {
    id: 8,
    name: "Green Velvet blazer",
    price: 99.99,
    category: "clothes",
    description: "",
    quantity: 1,
    rating: 4.8,
    img: "/images/products/23.jpg",
  },
  {
    id: 9,
    name: "Silvered high-heels",
    price: 32.01,
    category: "shoes",
    description: "",
    quantity: 1,
    rating: 2.5,
    img: "/images/products/15.jpg",
  },
  {
    id: 10,
    name: "gold mocassins",
    price: 132.11,
    category: "shoes",
    description: "",
    quantity: 1,
    rating: 3.8,
    img: "/images/products/17.jpg",
  },
  {
    id: 11,
    name: "Golden Gent's shoe",
    price: 128.19,
    category: "shoes",
    description: "",
    quantity: 1,
    rating: 1.6,
    img: "/images/products/8.jpg",
  },
  {
    id: 12,
    name: "Men's casual white sneakers",
    price: 35.09,
    category: "shoes",
    description: "",
    quantity: 1,
    rating: 3.4,
    img: "/images/products/1.jpg",
  },
];
