export const projectMenuItems = [
  {
    id: 1,
    title: "Birthday Remider",
    banner: "/screenshots/birthday-reminder.png",
    url: "/birthday-reminder",
  },
  {
    id: 2,
    title: "Tours",
    banner: "/screenshots/tours.png",
    url: "/tours",
  },
  {
    id: 3,
    title: "Reviews",
    banner: "/screenshots/reviews.png",
    url: "/reviews",
  },
  {
    id: 4,
    title: "Accordion",
    banner: "/screenshots/accordion.png",
    url: "/accordion",
  },
  {
    id: 5,
    title: "Menu Filter",
    banner: "/screenshots/menu-filter.png",
    url: "/menu-filter",
  },
  {
    id: 6,
    title: "Tabs",
    banner: "/screenshots/tabs.png",
    url: "/tabs",
  },
  {
    id: 7,
    title: "Slider",
    banner: "/screenshots/slider.png",
    url: "/slider",
  },
  {
    id: 8,
    title: "LoremGenerator",
    banner: "/screenshots/lorem.png",
    url: "/lorem-generator",
  },
  {
    id: 9,
    title: "Grocery Bud -Redux Toolkit",
    banner: "/screenshots/grocery-bud.png",
    url: "/grocery-bud",
  },
  {
    id: 10,
    title: "Responsive Navbar ",
    banner: "/screenshots/navbar.png",
    url: "/navbar",
  },
  {
    id: 11,
    title: "SideBar Modal",
    banner: "/screenshots/modal-sidebar.png",
    url: "/sidebar-modal",
  },
  {
    id: 12,
    title: "Stripe Menu ",
    banner: "/screenshots/stripe-menu.png",
    url: "/stripe-menu",
  },
  {
    id: 13,
    title: "Add To Cart",
    banner: "/screenshots/add-to-cart.png",
    url: "/cart",
  },
  {
    id: 14,
    title: "Theme Toggle",
    banner: "/screenshots/themeToggle.png",
    url: "/theme-toggle",
  },
  {
    id: 15,
    title: "Counter - Redux Toolkit",
    banner: "/screenshots/counter.png",
    url: "/counter",
  },
  {
    id: 16,
    title: "Todo App - Redux Toolkit",
    banner: "/screenshots/todoApp.png",
    url: "/todo-app",
  },
  {
    id: 17,
    title: "Form Validation",
    banner: "/screenshots/form-validation.png",
    url: "/form-validation",
  },
  {
    id: 18,
    title: "quiz App",
    banner: "/screenshots/quiz-app.png",
    url: "/quiz-app",
  },
  {
    id: 19,
    title: "Random Quotes",
    banner: "/screenshots/quote.png",
    url: "/random-quotes",
  },
  {
    id: 20,
    title: "Photo Gallery - Firebase",
    banner: "/screenshots/photo-gallery.png",
    url: "/photo-gallery",
  },
  {
    id: 21,
    title: "Firebase Authentication",
    banner: "/screenshots/firebase-auth.png",
    url: "/firebase-auth",
  },
  {
    id: 22,
    title: "React Crud - Context api",
    banner: "/screenshots/react-crud.png",
    url: "/react-crud",
  },
  {
    id: 23,
    title: "Firebase Crud",
    banner: "/screenshots/firebase-crud.png",
    url: "/firebase-crud",
  },
  {
    id: 24,
    title: "Login - Auth0",
    banner: "/screenshots/login_auth0.png",
    url: "/login",
  },
  {
    id: 25,
    title: "Github Users Github Users api",
    banner: "/screenshots/github-users.png",
    url: "/github-users",
  },
  {
    id: 26,
    title: "Github Jobs  Github Jobs api",
    banner: "/screenshots/github-jobs.png",
    url: "/github-jobs",
  },
  {
    id: 27,
    title: "Custom Pagination",
    banner: "/screenshots/pagination.png",
    url: "/pagination",
  },
  {
    id: 28,
    title: "Movie App TMDB api",
    banner: "/screenshots/movie_app.png",
    url: "/movie-app",
  },
  {
    id: 29,
    title: "Weather App",
    banner: "/screenshots/weather_app.png",
    url: "/weather-app",
  },
  {
    id: 30,
    title: "Recipe App Sponacular api",
    banner: "/screenshots/recipe-app.png",
    url: "/recipe-app",
  },
];
